/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.isu.cs2263.hw01;


import org.apache.commons.cli.*;

public class App {
    public static void main(String[] args) {
        Options options = new Options();
        options.addOption("h", "help", false, "print usage message");
        options.addOption("b", "batch", true, "batch file containing expressions to evaluate");
        options.addOption("o", "output", true, "output file");

        CommandLineParser parser = new DefaultParser();
        CommandLine cmd;

        try {
            cmd = parser.parse(options, args);
        }
        catch (Exception ex) {
            System.out.println("Exception while parsing command line arguments: ");
            ex.printStackTrace();
            return;
        }

        if (cmd.hasOption("h")) {
            HelpFormatter formatter = new HelpFormatter();
            formatter.printHelp("eval [OPTIONS]", "Evaluation of simple mathematical expressions", options, "\nCopyright (C) 2022 Tyson Cox");
            return;
        }

        if (cmd.hasOption("b")) {
            System.out.println("Batch value: " + cmd.getOptionValue("b"));
        }

        if (cmd.hasOption("o")) {
            System.out.println("Output value: " + cmd.getOptionValue("o"));
        }
    }
}
